name: build
on:
    push:
        branches: [ main ]


jobs:
    build_web:
        runs-on: ubuntu-latest
        steps:
            
            - name: print_working_directory
              run: pwd

            - name: hi
              run: echo "Hiiii!"
